#!/bin/bash

# Configure the localhost hostname to resolve to 127.0.0.2
sudo hostname localhost
sudo echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Configure facebook.com to resolve to 8.8.8.8
sudo echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
