#!/bin/bash

# Get the Docker network IP address
DOCKER_NETWORK_IP=$(ip addr show docker0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)

# Configure the localhost hostname to resolve to 127.0.0.2
sudo hostnamectl set-hostname localhost
sudo echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Configure facebook.com to resolve to 8.8.8.8
sudo echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Flush the DNS cache
sudo systemctl restart systemd-resolved

# Add the Docker network IP address to the DNS servers list
sudo sed -i "s/^#DNS=/DNS=/${DOCKER_NETWORK_IP},/g" /etc/resolv.conf
