#!/usr/bin/env bash

# Check if script is running in Docker
if grep -q 'docker' /proc/1/cgroup; then
  echo "Running in Docker, modifying hosts file"
  
  # Modify the hosts file entries
  sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
  sudo sed -i 's/facebook.com/8.8.8.8/g' /etc/hosts
  
  echo "Changes applied. Check using 'ping localhost' and 'ping facebook.com'"
else
  echo "This script is intended to run in a Docker environment."
fi
